import { MenuItem, Category } from "@/types";

export const categories: Category[] = [
  { id: "1", name: "All", image: "/images/all.png", description: "" },
  {
    id: "2",
    name: "Breakfast",
    image: "/images/breakfast.png",
    description: "",
  },
  { id: "3", name: "Lunch", image: "/images/lunch.png", description: "" },
  { id: "4", name: "Dinner", image: "/images/dinner.png", description: "" },
  { id: "5", name: "Drinks", image: "/images/drinks.png", description: "" },
  { id: "6", name: "Desserts", image: "/images/desserts.png", description: "" },
  { id: "7", name: "Snacks", image: "/images/snacks.png", description: "" },
  {
    id: "8",
    name: "Beverages",
    image: "/images/beverages.png",
    description: "",
  },
];

export const menuItems: MenuItem[] = [
  {
    id: "1",
    name: "Pancakes",
    description: "Fluffy pancakes served with maple syrup",
    price: 5.99,
    image: "/images/pancakes.png",
    category: "Breakfast",
    rating: 4.5,
    preparationTime: "15 mins",
    ingredients: ["Flour", "Eggs", "Milk", "Maple Syrup"],
    isVegetarian: true,
    isSpicy: false,
  },
  {
    id: "2",
    name: "Caesar Salad",
    description: "Fresh romaine lettuce with Caesar dressing",
    price: 7.99,
    image: "/images/caesar_salad.png",
    category: "Lunch",
    rating: 4.7,
    preparationTime: "10 mins",
    ingredients: ["Romaine Lettuce", "Caesar Dressing", "Croutons"],
    isVegetarian: true,
    isSpicy: false,
  },
  {
    id: "3",
    name: "Margherita Pizza",
    description: "Classic pizza with fresh mozzarella and basil",
    price: 12.99,
    image: "/images/margherita_pizza.png",
    category: "Dinner",
    rating: 4.8,
    preparationTime: "20 mins",
    ingredients: ["Pizza Dough", "Tomato Sauce", "Mozzarella", "Basil"],
    isVegetarian: true,
    isSpicy: false,
  },
  {
    id: "4",
    name: "Mojito",
    description: "Refreshing cocktail with mint and lime",
    price: 8.99,
    image: "/images/mojito.png",
    category: "Drinks",
    rating: 4.6,
    preparationTime: "5 mins",
    ingredients: ["Mint", "Lime", "Rum", "Soda Water"],
    isVegetarian: true,
    isSpicy: false,
  },
  {
    id: "5",
    name: "Chocolate Cake",
    description: "Rich chocolate cake with ganache",
    price: 4.99,
    image: "/images/chocolate_cake.png",
    category: "Desserts",
    rating: 4.9,
    preparationTime: "30 mins",
    ingredients: ["Flour", "Cocoa Powder", "Sugar", "Eggs"],
    isVegetarian: true,
    isSpicy: false,
  },
  {
    id: "6",
    name: "Nachos",
    description: "Crispy tortilla chips with cheese and jalapenos",
    price: 6.99,
    image: "/images/nachos.png",
    category: "Snacks",
    rating: 4.4,
    preparationTime: "10 mins",
    ingredients: ["Tortilla Chips", "Cheese", "Jalapenos"],
    isVegetarian: true,
    isSpicy: true,
  },
  {
    id: "7",
    name: "Iced Coffee",
    description: "Chilled coffee with milk and ice",
    price: 3.99,
    image: "/images/iced_coffee.png",
    category: "Beverages",
    rating: 4.3,
    preparationTime: "5 mins",
    ingredients: ["Coffee", "Milk", "Ice"],
    isVegetarian: true,
    isSpicy: false,
  },
];
